config/routes.rb
Jpt::Application.routes.draw do
  Rails.application.routes.draw do
    resources :tasks do
      put :sort, on: :collection
      collection {post :change_status, :ajax}
    end
  end
  get 'rorumenbas/new'
  get 'kanris/index'
  get 'kanri/index'
  get 'main/search'
  get 'helps' => 'helps#index'
  get 'edit_help' => 'helps#edit_help'
  post 'helps' => 'helps#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "confirm" => "sessions#send_mail"
  post "confirm" => "sessions#confirm_mail"
  get "login_code" => "sessions#login_code"
  post "login_code" => "sessions#login_code_confirm"
  match 'main', to: 'main#index', via: [:get]

  resources :bashokubunmsts, :bunruis, :dengonkaitous, :dengonyoukens, :ekis, :jpt_holiday_msts,\
            :kairanyokenmsts, :kaishamasters, :kikanmsts, :rorumasters, :setsubis, :shainmasters,\
            :shozokumasters, :tsushinseigyous, :yakushokumasters do
    collection do
      get :export_csv
      post :import
    end
  end

  resources :conversations do
    collection {post :update_message}
    resources :messages
  end
  resources :yuusens do
    collection {get :export_csv}
    collection {post :import, :ajax}
  end
  resources :paths do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :settings do
    collection {post :import, :ajax}
    collection {get :export_csv, :setting}
  end

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end  

  resources :dengons do
    collection {get :export_csv}
  end

  resources :main, only: [:index] do
    collection {get :search}
    collection {post :ajax}
  end

  resources :shoninshamsts  do
    collection {post :import, :ajax, :create_shonin}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search,:pdf_show,:sumikakunin}
    collection {post :import, :ajax}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_mybasho,:create_basho,:update_basho, :create_kaisha,:update_kaisha, :create_job, :update_job, :time_line_view, :import, :shutchou_create}
    collection {get :time_line_view, :pdf_event_show, :pdf_job_show, :pdf_koutei_show, :shutchou_ikkatsu_new}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :mybashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :myjobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :ajax, :import}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search, :import}
    collection {get :shonin_search, :pdf_show, :show_keihi_shuppi,:pdf_show_keihi_shuppi, :pdf_show_index}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import, :multi_delete, :ajax, :create_joutai, :update_joutai}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
    collection {post :import,:ajax}
    collection {get :export_csv}
  end

  resources :yuukyuu_kyuuka_rirekis do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :rorumenbas do
    collection { post :import}
    collection {get :export_csv}
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection { post :import }
      collection { get :export_csv }
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end

  resources :kintaiteeburus do
    collection {post :import,:ajax}
  end
  
  root to: 'main#index'
end

app/models/myjobmaster.rb
class Myjobmaster < ActiveRecord::Base
  self.table_name = :MYJOBマスタ
  self.primary_key = :job番号, :社員番号

  validates :job番号, uniqueness: {scope: :社員番号}
  validates :job番号, :job名, :社員番号, presence: true
  validates :入力社員番号, numericality: { only_integer: true }, inclusion: {in: proc{Shainmaster.pluck(:社員番号)}}, allow_blank: true
  validates :関連Job番号, numericality: { only_integer: true }, inclusion: {in: proc{Jobmaster.pluck(:job番号)}}, allow_blank: true
  validates :ユーザ番号, inclusion: {in: proc{Kaishamaster.pluck(:会社コード)}}, allow_blank: true
  validates :分類コード, inclusion: {in: proc{Bunrui.pluck(:分類コード)}}, allow_blank: true
  validate :check_input

  has_one :event, foreign_key: :JOB
  belongs_to :kaishamaster, class_name: :Kaishamaster, foreign_key: :ユーザ番号
  belongs_to :bunrui,foreign_key: :分類コード
  belongs_to :shainmaster, foreign_key: :社員番号
  belongs_to :jobmaster, foreign_key: :job番号
  # alias_attribute :id, :job番号
  # alias_attribute :job_name, :job名
  delegate :分類名, to: :bunrui, prefix: :bunrui, allow_nil: true

  # a class method import, with file passed through as an argument
  def self.import(file)
    # a block that runs through a loop in our CSV data
    CSV.foreach(file.path, headers: true) do |row|
      # creates a user for each row in the CSV file
      Myjobmaster.create! row.to_hash
    end
  end

  # def to_param
  #   id.parameterize
  # end
  #
  def self.to_csv
    attributes = %w{社員番号 job番号 job名 開始日 終了日 ユーザ番号 ユーザ名 入力社員番号 分類コード 分類名 関連Job番号 備考 updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |myjob|
        csv << attributes.map{ |attr| myjob.send(attr) }
      end
    end
  end

  def check_input
    errors.add(:終了日, (I18n.t 'app.model.check_data_input')) if 開始日.present? && 終了日.present? && 開始日 > 終了日
  end
end

app/controllers/myjobmasters_controller.rb
class MyjobmastersController < ApplicationController
  before_action :require_user!
  before_action :set_myjobmaster, only: [:show, :edit, :update]
  before_action :set_refer, only: [:new, :edit, :create, :update]
  load_and_authorize_resource except: [:export_csv, :destroy]
  respond_to :js

  include MyjobmastersHelper

  # GET /jobmasters
  # GET /jobmasters.json
  def index
    @myjobmasters = Myjobmaster.all.order('updated_at desc')
  end

  # GET /jobmasters/1
  # GET /jobmasters/1.json
  def show
  end

  # GET /jobmasters/new
  def new

    @myjobmaster = Myjobmaster.new
  end

  # GET /jobmasters/1/edit
  def edit
  end

  # POST /jobmasters
  # POST /jobmasters.json
  def create
    # max_job = Jobmaster.pluck(:job番号).map {|i| i.to_i}.max + 1
    # max_job = 100001 if max_job < 100001
    # jobmaster_params[:job番号] = max_job
    @myjobmaster = Myjobmaster.new(myjobmaster_params)
    flash[:notice] = t 'app.flash.new_success' if @myjobmaster.save
    respond_with @myjobmaster, location: myjobmasters_url
  end

  # PATCH/PUT /jobmasters/1
  # PATCH/PUT /jobmasters/1.json
  def update
    flash[:notice] = t 'app.flash.update_success' if @myjobmaster.update(myjobmaster_params)
    respond_with @myjobmaster, location: myjobmasters_url
  end

  # DELETE /jobmasters/1
  # DELETE /jobmasters/1.json
  def destroy
    if params[:ids]
      begin
        params[:ids].each { |id| Myjobmaster.find(id).try(:destroy) }
      rescue
      end
      data = { destroy_success: 'success' }
      respond_to do |format|
        format.json { render json: data}
      end
    else
      begin
        @myjobmaster = Myjobmaster.find(params[:id])
        @myjobmaster.destroy if @myjobmaster
        respond_with @myjobmaster, location: myjobmasters_url
      rescue
      end
    end
  end

  def ajax
    case params[:focus_field]
      when 'myjobmaster_ユーザ番号'
        kaisha_name = Kaishamaster.find(params[:kaisha_code]).try :name
        data = {kaisha_name: kaisha_name}
        respond_to do |format|
          format.json { render json: data}
        end
      when 'myjob_削除する'
        myjobIds = params[:myjobs]
        myjobIds.each{ |myjobId|
          Myjobmaster.find(myjobId).destroy          
        }        
        data = {destroy_success: 'success'}
        respond_to do |format|
          format.json { render json: data}
        end
      else
    end
  end

  def import
    if params[:file].nil?
      flash[:alert] = t 'app.flash.file_nil'
      redirect_to myjobmasters_path
    elsif File.extname(params[:file].original_filename) != '.csv'
      flash[:danger] = t 'app.flash.file_format_invalid'
      redirect_to myjobmasters_path
    else
      begin
        Myjobmaster.transaction do
          Myjobmaster.delete_all
          Myjobmaster.reset_pk_sequence
          Myjobmaster.import(params[:file])
          notice = t 'app.flash.import_csv'
          redirect_to :back, notice: notice
        end
      rescue => err
        flash[:danger] = err.to_s
        redirect_to myjobmasters_path
      end
    end
  end

  def export_csv
    @myjobs = Myjobmaster.all

    respond_to do |format|
      format.html
      format.csv { send_data @myjobs.to_csv, filename: 'myjobマスタ.csv' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myjobmaster
      @myjobmaster = Myjobmaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myjobmaster_params
      params.require(:myjobmaster).permit(:社員番号,:job番号, :job名, :開始日, :終了日, :ユーザ番号, :ユーザ名, :入力社員番号, :分類コード, :分類名, :関連Job番号, :備考)
    end

  def set_refer
    @kaishamasters = Kaishamaster.all
    @jobs = Jobmaster.includes(:bunrui)
    @shains = Shainmaster.all
    @bunruis = Bunrui.all
  end
end

app/helpers/myjobmasters_helper.rb
module MyjobmastersHelper
  def check_existing?(hash_param)
    ret1 = Shainmaster.exists?(hash_param[:入力社員番号])
    ret2 = MyJobmaster.exists?(hash_param[:関連Job番号])
    ret = ret1 && ret2
  end
end

app/views/myjobmasters/_form.html.haml
= javascript_include_tag 'myjobmasters/form'
= stylesheet_link_tag 'myjobmst'
.editor-datetime
  = simple_form_for @myjobmaster do |f|
    .col-sm-3.col-sm-offset-1
      = f.association :shainmaster, label_method: :氏名, value_method: :社員番号, label:'社員番号' if mode == :new
      = f.input :job番号 if mode == :new
      = f.input :job名
      = f.input :開始日, as: :date_picker
      = f.input :終了日, as: :date_picker
      = f.input :ユーザ番号, as: :search_field
      = f.input :ユーザ名
    .col-sm-3.col-sm-offset-2
      = f.input :入力社員番号, hint:'', hint_html: {class: 'hint-shain-refer'}, as: :search_field
      = f.association :bunrui, label_method: :分類名, value_method: :分類コード, label:'分類'
      = f.input :関連Job番号, hint:'', hint_html: {class: 'hint-job-refer'}, as: :search_field
      = f.input :備考, as: :text
      = f.button :submit, class: 'btn btn-primary'

= render 'share/kaisha_modal'
= render 'share/job_modal'
= render 'share/shain_modal_refer'

app/views/myjobmasters/edit.html.erb
<%provide(:title, (t 'title.myjobmaster'))%>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to 'MYJOBマスタ', myjobmasters_path %></li>
  <li class="active">編集</li>
</ol>

<%= render 'form', mode: :edit %>

app/views/myjobmasters/index.html.erb
<%= javascript_include_tag 'myjobmasters/index' %>
<%= stylesheet_link_tag 'myjobmst' %>
<%provide(:title, (t 'title.myjobmaster'))%>
<script>
    current_user_id = <%= current_user.id %>
    current_user_id = current_user_id.toString()
</script>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">MYJOBマスタ</li>
</ol>

<table id="myjobmaster" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>Job番号</th>
      <th>Job名</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>ユーザ番号</th>
      <th>ユーザ名</th>
      <th>入力社員番号</th>
      <th>分類コード</th>
      <!--<th>分類名</th>-->
      <th>関連Job番号</th>
      <th>備考</th>
      <th>更新日</th>
      <!--<th></th>-->
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @myjobmasters.each do |myjobmaster| %>
      <tr id="myjobmaster_<%= myjobmaster.id %>">
        <td><%= myjobmaster.社員番号 %></td>
        <td><%= myjobmaster.job番号 %></td>
        <td><%= myjobmaster.job名 %></td>
        <td><%= myjobmaster.開始日.try(:strftime, '%Y/%m/%d') %></td>
        <td><%= myjobmaster.終了日.try(:strftime, '%Y/%m/%d') %></td>
        <td><%= myjobmaster.ユーザ番号 %></td>
        <td><%= myjobmaster.ユーザ名 %></td>
        <td><%= myjobmaster.入力社員番号 %></td>
        <td><%= myjobmaster.分類コード %></td>
        <!--<td><%# myjobmaster.分類名 %></td>-->
        <td><%= myjobmaster.関連Job番号 %></td>
        <td><%= myjobmaster.備考 %></td>
        <td><%= myjobmaster.updated_at.try(:strftime, '%Y/%m/%d %H:%M:%S') %></td>
        <!--<td><%# link_to '詳細', myjobmaster %></td>-->
        <td><%= link_to '', edit_myjobmaster_path(myjobmaster), class: "glyphicon glyphicon-edit remove-underline" %></td>
        <td><%= link_to '', myjobmaster, method: :delete, data: { confirm: '削除して宜しいですか？' } , class: "glyphicon glyphicon-remove text-danger remove-underline" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :update, @myjobmasters %>
  <%=render 'share/import_csv_modal',import_path: import_myjobmasters_path%>
<% end %>

app/views/myjobmasters/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to 'MYJOBマスタ', myjobmasters_path %></li>
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">新規</li>
</ol>

<%= render 'form', mode: :new %>
<%provide(:title, (t 'title.myjobmaster'))%>

app/views/myjobmasters/show.html.erb
<p>
  <strong>社員番号:</strong>
  <%= @myjobmaster.社員番号 %>
</p>
<p>
  <strong>JOB番号:</strong>
  <%= @myjobmaster.job番号 %>
</p>

<p>
  <strong>JOB名:</strong>
  <%= @myjobmaster.job名 %>
</p>

<p>
  <strong>開始日:</strong>
  <%= @myjobmaster.開始日 %>
</p>

<p>
  <strong>終了日:</strong>
  <%= @myjobmaster.終了日 %>
</p>

<p>
  <strong>ユーザ番号:</strong>
  <%= @myjobmaster.ユーザ番号 %>
</p>

<p>
  <strong>ユーザ名:</strong>
  <%= @myjobmaster.ユーザ名 %>
</p>
<p>
  <strong>更新日:</strong>
  <%= @myjobmaster.updated_at %>
</p>

<%= link_to '編集', edit_myjobmaster_path(@myjobmaster) %> |
<%= link_to '戻る', myjobmasters_path %>
<%provide(:title, (t 'title.myjobmaster'))%>