config/routes.rb
Jpt::Application.routes.draw do
  Rails.application.routes.draw do
    resources :tasks do
      put :sort, on: :collection
      collection {post :change_status, :ajax}
    end
  end
  get 'rorumenbas/new'
  get 'kanris/index'
  get 'kanri/index'
  get 'main/search'
  get 'helps' => 'helps#index'
  get 'edit_help' => 'helps#edit_help'
  post 'helps' => 'helps#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "confirm" => "sessions#send_mail"
  post "confirm" => "sessions#confirm_mail"
  get "login_code" => "sessions#login_code"
  post "login_code" => "sessions#login_code_confirm"
  match 'main', to: 'main#index', via: [:get]

  resources :bashokubunmsts, :bunruis, :dengonkaitous, :dengonyoukens, :ekis, :jpt_holiday_msts,\
            :kairanyokenmsts, :kaishamasters, :kikanmsts, :rorumasters, :setsubis, :shainmasters,\
            :shozokumasters, :tsushinseigyous, :yakushokumasters do
    collection do
      get :export_csv
      post :import
    end
  end

  resources :conversations do
    collection {post :update_message}
    resources :messages
  end
  resources :yuusens do
    collection {get :export_csv}
    collection {post :import, :ajax}
  end
  resources :paths do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :settings do
    collection {post :import, :ajax}
    collection {get :export_csv, :setting}
  end

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end  

  resources :dengons do
    collection {get :export_csv}
  end

  resources :main, only: [:index] do
    collection {get :search}
    collection {post :ajax}
  end

  resources :shoninshamsts  do
    collection {post :import, :ajax, :create_shonin}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search,:pdf_show,:sumikakunin}
    collection {post :import, :ajax}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_mybasho,:create_basho,:update_basho, :create_kaisha,:update_kaisha, :create_job, :update_job, :time_line_view, :import, :shutchou_create}
    collection {get :time_line_view, :pdf_event_show, :pdf_job_show, :pdf_koutei_show, :shutchou_ikkatsu_new}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :mybashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :myjobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :ajax, :import}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search, :import}
    collection {get :shonin_search, :pdf_show, :show_keihi_shuppi,:pdf_show_keihi_shuppi, :pdf_show_index}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import, :multi_delete, :ajax, :create_joutai, :update_joutai}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
    collection {post :import,:ajax}
    collection {get :export_csv}
  end

  resources :yuukyuu_kyuuka_rirekis do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :rorumenbas do
    collection { post :import}
    collection {get :export_csv}
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection { post :import }
      collection { get :export_csv }
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end

  resources :kintaiteeburus do
    collection {post :import,:ajax}
  end
  
  root to: 'main#index'
end

app/models/dengon.rb
class Dengon < ActiveRecord::Base
  self.table_name = :伝言
  include PgSearch
  multisearchable :against => %w{from1 from2 input_user_氏名 to_user_氏名 youken_種類名 kaitou_種類名 伝言内容}

  validates :入力者, :社員番号, presence: true
  belongs_to :input_user, foreign_key: :入力者, class_name: 'Shainmaster'
  belongs_to :to_user, foreign_key: :社員番号, class_name: 'Shainmaster'
  belongs_to :dengonyouken, foreign_key: :用件, class_name: 'Dengonyouken'
  belongs_to :dengonkaitou, foreign_key: :回答, class_name: 'Dengonkaitou'

  delegate :氏名, to: :input_user, prefix: :input_user, allow_nil: true
  delegate :氏名, to: :to_user, prefix: :to_user, allow_nil: true
  delegate :種類名, to: :dengonyouken, prefix: :youken, allow_nil: true
  delegate :種類名, to: :dengonkaitou, prefix: :kaitou, allow_nil: true

  def self.to_csv
    attributes = %w{id from1 from2 日付 入力者 用件 回答 伝言内容 確認 送信 社員番号}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |dengon|
        csv << attributes.map{ |attr| dengon.send(attr) }
      end
    end
  end

  # Naive approach
  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end

end

app/controllers/dengons_controller.rb
class DengonsController < ApplicationController
  before_action :require_user!
  before_action :set_dengon, only: [:show, :edit, :update, :destroy]

  respond_to :html
  include DengonsHelper

  def index
    vars = request.query_parameters
    @dengons = Dengon.includes(:input_user, :to_user, {dengonyouken: :yuusen}, :dengonkaitou)
    @shain_param = params[:head].present? ? params[:head][:shainbango] : session[:user]
    @nyuuryokusha = params[:head][:nyuuryokusha] if params[:head].present?
    @yoken = params[:head][:youken] if params[:head].present?
    @kaitou = params[:head][:kaitou] if params[:head].present?

    @dengons = @dengons.where('社員番号 = ?', @shain_param) if @shain_param.present? && vars['search'].nil?
    if !vars['search'].nil?
      @shain_param = ''
    end
    @dengons = @dengons.where(用件: @yoken) if @yoken.present?
    @dengons = @dengons.where(回答: @kaitou) if @kaitou.present?
    @dengons = @dengons.where(入力者: @nyuuryokusha) if @nyuuryokusha.present?
    respond_with(@dengons)
  end

  def show
    respond_with(@dengon)
  end

  def new
    @dengon = Dengon.new
    @dengon.input_user = Shainmaster.find session[:user]
    respond_with(@dengon)
  end

  def edit
  end

  def create
    @dengon = Dengon.new(dengon_params)
    if @dengon.save
      send_notify_mail(@dengon)    
      update_dengon_counter dengon_params
      notify_to(nil, @dengon.社員番号)
    end
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = t 'app.flash.mail_to'
  rescue Net::SMTPFatalError
    flash[:notice] = t 'app.flash.mail_send_field'
  ensure
    redirect_to dengons_url
  end

  def update
    mail_has_send = @dengon.送信
    if @dengon.update(dengon_params)
      unless mail_has_send
        send_notify_mail(@dengon)
      end
      update_dengon_counter dengon_params
    end

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = t 'app.flash.mail_to'
  rescue Net::SMTPFatalError
    flash[:notice] = t 'app.flash.mail_send_field'
  ensure
    redirect_to dengons_url
  end

  def destroy
    shainbango = Dengon.find(params[:id]).社員番号
    @dengon.destroy()
    update_dengon_counter_with_id shainbango
    respond_with(@dengon)
  end

  def export_csv
    @dengons = Dengon.all

    respond_to do |format|
      format.csv { send_data @dengons.to_csv, filename: '伝言.csv' }
    end
  end

  private
    def set_dengon
      @dengon = Dengon.find(params[:id])
    end

    def dengon_params
      params.require(:dengon).permit(:from1, :from2, :日付, :入力者, :社員番号, :用件, :回答, :伝言内容, :確認, :送信)
    end

    def send_notify_mail(dengon)
      if dengon.送信
          begin
            mail_to = dengon.to_user.tsushinseigyou.メール
          rescue
            mail_to = ""
          end

          begin
            mail_body = "#{dengon.try(:日付).strftime('%F %H:%M')} \r\n"
          rescue
            mail_body = ""
          end
          mail_body << "\r\n"
          mail_body << "#{dengon.try(:from1)} #{dengon.try(:from2)} \r\n"
          mail_body << "\r\n"
          mail_body << "#{dengon.dengonyouken.try(:種類名)} #{dengon.dengonkaitou.try(:種類名)} \r\n"
          mail_body << "\r\n"
          mail_body << "#{dengon.try(:伝言内容)} \r\n"
          mail_body << "\r\n"
          mail_body << "\r\n"
          mail_body << "[#{dengon.input_user.try(:氏名)}]"
          mail_body.gsub('\r\n','<br />')
          
          SendMailJob.perform_later(mail_to.to_s, 'SkyBordTricom@gmail.com', 'From Web_TRICOM', mail_body.to_s )
        end
    end
end

app/helpers/dengons_helper.rb
module DengonsHelper
  def update_dengon_counter dengon_params
    counter = Dengon.where(社員番号: dengon_params[:社員番号], 確認: false).count
    Shainmaster.find(dengon_params[:社員番号]).update(伝言件数: counter)
  end

  def update_dengon_counter_with_id shainbango
    if !shainbango.nil? && shainbango!=''
      counter = Dengon.where(社員番号: shainbango, 確認: false).count
      Shainmaster.find(shainbango).update(伝言件数: counter)
    end
  end

  def send_mail(to_mail, subject_mail, body_mail)
    Mail.deliver do
      to to_mail
      from 'skybord@jpt.co.jp'
      subject subject_mail
      body body_mail
    end
  end
end

app/views/dengons/_form.html.haml
= javascript_include_tag 'dengons/form'
= simple_form_for(@dengon) do |f|
  = f.error_notification
  .col-md-3.col-xs-3.col-sm-3.col-lg-3.col-md-offset-2.col-xs-offset-2.col-sm-offset-2.col-lg-offset-2
    = f.input :from1, label: (t 'title.aitesaki')
    = f.input :from2, label: (t 'title.namae')
    = f.input :日付, label: (t 'title.hidzuke'), as: :date_time_picker
    = f.association :input_user, label_method: :氏名, value_method: :社員番号, label: (t 'title.nyuuryokusha')
    = f.association :to_user, label_method: :氏名, value_method: :社員番号, label: (t 'title.shain')
    = f.association :dengonyouken, label: (t 'title.youken'), collection: Dengonyouken.includes(:yuusen).order(:優先さ).collect { |k| [k.種類名, k.id, {:style => "background-color: "+k.yuusen.try(:色).to_s+"; color: Black"}] }
    = f.association :dengonkaitou, label_method: :種類名, value_method: :id, label: (t 'title.kaitou'), collection: Dengonkaitou.all.order(:備考)
  .col-md-3.col-xs-3.col-sm-3.col-lg-3.col-md-offset-1.col-xs-offset-1.col-sm-offset-1.col-lg-offset-1
    = f.input :伝言内容, label: (t 'title.dengonnaiyou'), as: :text, :input_html => { :rows => 10, :cols => 256, :class => 'dengon-naiyo' }
    = f.input :確認, label: (t 'helpers.button.confirm')
    = f.input :送信, label: (t 'title.shousin')

    = f.button :submit, class:'btn btn-primary', id: 'dengon_touroku'
    = link_to t('helpers.button.cancel'),dengons_path,class: "btn btn-primary"

app/views/dengons/_header.html.haml
- shains = Shainmaster.pluck(:氏名, :社員番号)
.row-fruid
  .form-inline
    .form-group
      = label_tag (t 'title.nyuuryokusha')
      = select(:head, :nyuuryokusha, shains, {selected: @nyuuryokusha, include_blank: true }, class: 'form-control')
    .form-group
      = label_tag (t 'title.shain')
      = select(:head, :shainbango, shains, {selected: @shain_param, include_blank: true }, class: 'form-control')
    .form-group
      = label_tag (t 'title.youkendengon')
      = select(:head, :youken, Dengonyouken.includes(:yuusen).collect {|p| [ p.種類名, p.id, {:style => "background-color: "+p.yuusen.try(:色).to_s+"; color: Black"} ] }, {selected: @yoken, include_blank: true }, class: 'form-control')
    .form-group
      = label_tag (t 'title.kaitou')
      = select(:head, :kaitou, Dengonkaitou.pluck(:種類名, :id), {selected: @kaitou, include_blank: true }, class: 'form-control')
    .form-group
      = button_tag (t 'title.kensaku'), class:'btn btn-primary'

app/views/dengons/edit.html.haml
= provide(:title, (t 'title.dengon'))
%ol.breadcrumb
  %li= link_to (t 'title.menu'), main_path
  %li= link_to (t 'title.dengon') , dengons_path
  %li.active= (t 'title.edit')

= render 'form'

app/views/dengons/index.html.haml
= javascript_include_tag 'dengons/index'
= provide(:title, (t 'title.dengon'))
%ol.breadcrumb
  %li= link_to (t 'title.menu'), main_path
  %li.active= (t 'title.dengon')
  .navbar-nav.navbar-right
    %li.dropdown{:style => "margin-right: 20px"}
      %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
        %span
          %i.glyphicon.glyphicon-question-sign.fa-1x{:style => "color: rgb(76, 76, 76); font-size: 20px"}
      %ul.dropdown-menu.help-question{:style => "width: 500px"}
        %li{:style => "text-align: center; font-size: 20px"}
          %b 伝言
        %li ☆　社員が自分に来た伝言を確認できるようにする。
        %li ☆　未確認の伝言がある場合、カレンダー画面の伝言欄にその件数が表示される。
        %li 相手先：通常は、相手先の会社名などを入力
        %li 名前：相手先の名前
        %li 日付：電話がかかってきた日付と時刻（タイムスタンプ）
        %li 入力者：この伝言を記入している社員の社員番号
        %li 社員：伝言の相手先の社員番号（社員マスタから選択入力）
        %li 用件：伝言用件マスタから選択入力
        %li 回答：伝言回答マスタからの選択入力
        %li 伝言内容：伝言内容（メモ内容）を入力
        %li 確認：toの社員が伝言内容を確認したときにチェックを入力
        %li 送信： "伝言管理マスタの送信区分が""1""（送信OK)の場合に自動的にチェックを入れる。後で見直して、送信済みを確認するため。"

= form_for :dengon, url: dengons_path, html: {class:'form-inline'}, method: :get do |f|
  = render 'header', f:f
  %br
  %table.dengon.table.table-striped.table-bordered.table-hover{cellspacing: 0, width: '100%' }
    %thead
      %tr
        %th= (t 'title.aitesaki')
        %th= (t 'title.namae')
        %th= (t 'title.hidzuke')
        %th= (t 'title.nyuuryokusha')
        %th= (t 'title.shain')
        %th= (t 'title.youken')
        %th= (t 'title.kaitou')
        %th= (t 'title.dengonnaiyou')
        %th= (t 'helpers.button.confirm')
        %th= (t 'title.shousin')
        %th
        %th

    %tbody
      - @dengons.each do |dengon|
        %tr
          %td= dengon.from1
          %td= dengon.from2
          %td= dengon.日付.strftime("%Y/%m/%d %H:%M" ) if dengon.日付
          %td= dengon.input_user_氏名
          %td= dengon.to_user_氏名
          %td{:style => "background-color: "+dengon.dengonyouken.try(:yuusen).try(:色).to_s+"; color: Black"}= dengon.youken_種類名
          %td= dengon.kaitou_種類名
          - if dengon.確認
            %td{style: "white-space: pre-line;"}= dengon.伝言内容
          - else
            %td{style: "white-space: pre-line;"}
              %b= dengon.伝言内容
          %td= dengon.確認 == true ? (t 'title.kakuninzu'):'未確認'
          %td= dengon.送信 == true ? '済' : ''
          %td= link_to '', edit_dengon_path(dengon), class: "glyphicon glyphicon-edit remove-underline"
          %td= link_to '', dengon, :method => :delete, :data => { :confirm => (t 'title.delete_confirm') } , class: "glyphicon glyphicon-remove text-danger remove-underline"

app/views/dengons/new.html.haml
= provide(:title, (t 'title.dengon'))
%ol.breadcrumb
  %li= link_to (t 'title.menu'), main_path
  %li= link_to (t 'title.dengon'), dengons_path
  %li.active= (t 'title.new')

= render 'form'

app/views/dengons/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @dengon.first_name
%p
  %b Last name:
  = @dengon.last_name

= link_to (t 'title.edit'), edit_dengon_path(@dengon)
\|
= link_to (t 'title.modoru'), dengons_path
= provide(:title, (t 'title.dengon'))