config/routes.rb
Jpt::Application.routes.draw do
  Rails.application.routes.draw do
    resources :tasks do
      put :sort, on: :collection
      collection {post :change_status, :ajax}
    end
  end
  get 'rorumenbas/new'
  get 'kanris/index'
  get 'kanri/index'
  get 'main/search'
  get 'helps' => 'helps#index'
  get 'edit_help' => 'helps#edit_help'
  post 'helps' => 'helps#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "confirm" => "sessions#send_mail"
  post "confirm" => "sessions#confirm_mail"
  get "login_code" => "sessions#login_code"
  post "login_code" => "sessions#login_code_confirm"
  match 'main', to: 'main#index', via: [:get]

  resources :bashokubunmsts, :bunruis, :dengonkaitous, :dengonyoukens, :ekis, :jpt_holiday_msts,\
            :kairanyokenmsts, :kaishamasters, :kikanmsts, :rorumasters, :setsubis, :shainmasters,\
            :shozokumasters, :tsushinseigyous, :yakushokumasters do
    collection do
      get :export_csv
      post :import
    end
  end

  resources :conversations do
    collection {post :update_message}
    resources :messages
  end
  resources :yuusens do
    collection {get :export_csv}
    collection {post :import, :ajax}
  end
  resources :paths do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :settings do
    collection {post :import, :ajax}
    collection {get :export_csv, :setting}
  end

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end  

  resources :dengons do
    collection {get :export_csv}
  end

  resources :main, only: [:index] do
    collection {get :search}
    collection {post :ajax}
  end

  resources :shoninshamsts  do
    collection {post :import, :ajax, :create_shonin}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search,:pdf_show,:sumikakunin}
    collection {post :import, :ajax}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_mybasho,:create_basho,:update_basho, :create_kaisha,:update_kaisha, :create_job, :update_job, :time_line_view, :import, :shutchou_create}
    collection {get :time_line_view, :pdf_event_show, :pdf_job_show, :pdf_koutei_show, :shutchou_ikkatsu_new}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :mybashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :myjobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :ajax, :import}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search, :import}
    collection {get :shonin_search, :pdf_show, :show_keihi_shuppi,:pdf_show_keihi_shuppi, :pdf_show_index}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import, :multi_delete, :ajax, :create_joutai, :update_joutai}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
    collection {post :import,:ajax}
    collection {get :export_csv}
  end

  resources :yuukyuu_kyuuka_rirekis do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :rorumenbas do
    collection { post :import}
    collection {get :export_csv}
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection { post :import }
      collection { get :export_csv }
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end

  resources :kintaiteeburus do
    collection {post :import,:ajax}
  end
  
  root to: 'main#index'
end

app/models/jpt_holiday_mst.rb
class JptHolidayMst < ActiveRecord::Base
  include PgSearch
  multisearchable :against => %w{title description}  
  validates :event_date, presence: true, uniqueness: true
  def self.import(file)
    # a block that runs through a loop in our CSV data
    CSV.foreach(file.path, headers: true) do |row|
      # creates a user for each row in the CSV file
      JptHolidayMst.create! row.to_hash
    end
  end
  def self.to_csv
    attributes = %w{event_date title description}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |jpt_holiday|
        csv << attributes.map{ |attr| jpt_holiday.send(attr) }
      end
    end
  end
  # Naive approach
  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end
end

app/controllers/jpt_holiday_msts_controller.rb
class JptHolidayMstsController < ApplicationController
  before_action :require_user!
  load_and_authorize_resource except: [:export_csv, :update, :destroy]
  respond_to :js,:html

  def index
    @jpt_holiday_msts = JptHolidayMst.all
    respond_with(@jpt_holiday_msts)
  end

  def create
    @jpt_holiday_mst = JptHolidayMst.new(jpt_holiday_mst_params)
    flash[:notice] = t 'app.flash.new_success' if @jpt_holiday_mst.save
    puts @jpt_holiday_mst.errors.full_messages
    respond_with(@jpt_holiday_mst)
  end

  def update
    @jpt_holiday_mst = JptHolidayMst.find_by(id: jpt_holiday_mst_params[:id])
    flash[:notice] = t 'app.flash.update_success' if @jpt_holiday_mst.update(jpt_holiday_mst_params)
    respond_with(@jpt_holiday_mst)
  end

  def destroy
    if params[:ids]
      JptHolidayMst.where(id: params[:ids]).destroy_all
      data = { destroy_success: 'success' }
      respond_to do |format|
        format.json { render json: data }
      end
    else
      @jpt_holiday_mst = JptHolidayMst.find_by_id(params[:id])
      @jpt_holiday_mst.destroy if @jpt_holiday_mst
      respond_with(@jpt_holiday_mst, location: jpt_holiday_msts_path)
    end
  end

  def import
    if params[:file].nil?
      flash[:alert] = t 'app.flash.file_nil'
      redirect_to jpt_holiday_msts_path
    elsif File.extname(params[:file].original_filename) != '.csv'
      flash[:danger] = t 'app.flash.file_format_invalid'
      redirect_to jpt_holiday_msts_path
    else
      begin
        JptHolidayMst.transaction do
          JptHolidayMst.delete_all
          JptHolidayMst.reset_pk_sequence
          JptHolidayMst.import(params[:file])
          notice = t 'app.flash.import_csv'
          redirect_to :back, notice: notice
        end
      rescue => err
        flash[:danger] = err.to_s
        redirect_to jpt_holiday_msts_path
      end
    end
  end

  def export_csv
    @jpt_holidays = JptHolidayMst.all
    respond_to do |format|
      format.csv { send_data @jpt_holidays.to_csv, filename: 'ジュピター休日.csv' }
    end
  end

  private

  def set_jpt_holiday_mst
    @jpt_holiday_mst = JptHolidayMst.find_by id: params[:id]
  end

  def jpt_holiday_mst_params
    params.require(:jpt_holiday_mst).permit(:id, :event_date, :title, :description)
  end

end

app/helpers/jpt_holiday_msts_helper.rb
module JptHolidayMstsHelper
end

app/views/jpt_holiday_msts/_edit.html.haml
.modal#holiday-edit-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel ジュピター休日編集
      .modal-body
        = simple_form_for :jpt_holiday_mst, url: jpt_holiday_mst_path(id: 0), method: :patch, :remote => true, html: { id: 'edit_jpt_holiday_mst', role: :form, 'data-model' => 'jpt_holiday_mst'} do |f|
          = f.input :ID, as: :hidden do
            = f.input_field :id, class: 'form-control'
            .span.help-block
          = f.input :event_date, label: '休日' do
            = f.input_field :event_date, as: :date_time_picker, class: 'form-control'
            .span.help-block
          = f.input :title, label: 'タイトル' do
            = f.input_field :title, class: 'form-control'
            .span.help-block
          = f.input :description, label: '備考' do
            = f.input_field :description, class: 'form-control'
            .span.help-block
          = f.button :submit, class: 'btn btn-primary'

app/views/jpt_holiday_msts/_holiday_edit_modal.html.haml
.modal#holiday-edit-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel ジュピター休日編集
      .modal-body
        = simple_form_for JptHolidayMst.new, url: update_holiday_jpt_holiday_msts_path, :remote => true, html: { id: 'edit_jpt_holiday_mst', role: :form, 'data-model' => 'jpt_holiday_mst'} do |f|
          = f.input :ID, as: :hidden do
            = f.input_field :id, class: 'form-control'
            .span.help-block
          = f.input :休日 do
            = f.input_field :event_date, class: 'form-control'
            .span.help-block
          = f.input :タイトル do
            = f.input_field :title, class: 'form-control'
            .span.help-block
          = f.input :備考 do
            = f.input_field :description, class: 'form-control'
            .span.help-block
          = f.button :submit, class: 'btn btn-primary'

app/views/jpt_holiday_msts/_holiday_new_modal.html.haml
.modal#holiday-new-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel ジュピター休日新規
      .modal-body
        = simple_form_for JptHolidayMst.new, url: create_holiday_jpt_holiday_msts_path, :remote => true, html: {role: :form, 'data-model' => 'jpt_holiday_mst'} do |f|
          / = f.input :ID do
          /   = f.input_field :id, class: 'form-control'
          /   .span.help-block
          = f.input :休日 do
            = f.input_field :event_date, class: 'form-control'
            .span.help-block
          = f.input :タイトル do
            = f.input_field :title, class: 'form-control'
            .span.help-block
          = f.input :備考 do
            = f.input_field :description, class: 'form-control'
            .span.help-block
          = f.button :submit, class: 'btn btn-primary'

app/views/jpt_holiday_msts/_new.html.haml
.modal#holiday-new-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel ジュピター休日新規
      .modal-body
        = simple_form_for :jpt_holiday_mst, url: jpt_holiday_msts_path, method: :post, :remote => true, html: { id: 'new_jpt_holiday_mst', role: :form, 'data-model' => 'jpt_holiday_mst'} do |f|
          = f.input :event_date, label: '休日' do
            = f.input_field :event_date, as: :date_time_picker, class: 'form-control'
            .span.help-block
          = f.input :title, label: 'タイトル' do
            = f.input_field :title, class: 'form-control'
            .span.help-block
          = f.input :description, label: '備考' do
            = f.input_field :description, class: 'form-control'
            .span.help-block
          = f.button :submit, class: 'btn btn-primary'

app/views/jpt_holiday_msts/create.js.erb
model = 'jpt_holiday_mst'

$('form#new_' + model).clear_previous_errors()

<% if @jpt_holiday_mst.errors.any? %>
  $('form#new_' + model).render_form_errors(model, '<%=@jpt_holiday_mst.errors.messages.to_json.html_safe%>')
<% else %>
  $('#holiday-new-modal').modal('hide');
  $('#holiday_table').DataTable().row.add( [
    "<%=@jpt_holiday_mst.id%>",
    "<%=@jpt_holiday_mst.event_date.try(:strftime, '%Y/%m/%d')%>",
    "<%=@jpt_holiday_mst.title%>",
    "<%=@jpt_holiday_mst.description%>"
  ]).draw( false );
<% end %>

app/views/jpt_holiday_msts/create_holiday.js.erb
model = 'jpt_holiday_mst'

$('form#new_' + model).clear_previous_errors()

<% if @jpt_holiday_mst.errors.any? %>
  $('form#new_' + model).render_form_errors(model, '<%=@jpt_holiday_mst.errors.messages.to_json.html_safe%>')
<% else %>
  $('#holiday-new-modal').modal('hide');
  $('#holiday_table').DataTable().row.add( [
    "<%=@jpt_holiday_mst.id%>",
    "<%=@jpt_holiday_mst.event_date%>",
    "<%=@jpt_holiday_mst.title%>",
    "<%=@jpt_holiday_mst.description%>"
  ]).draw( false );
<% end %>

app/views/jpt_holiday_msts/index.html.erb
<%= javascript_include_tag 'jpt_holiday_msts/index' %>
<%provide(:title, (t 'title.jpt_hokiday_mst'))%>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li class="active">ジュピター休日</li>
</ol>
<table id="holiday_table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>ID</th>
    <th>休日</th>
    <th>タイトル</th>
    <th>備考</th>
  </tr>
  </thead>

  <tbody>
  <% @jpt_holiday_msts.each do |jpt_holiday_mst| %>
      <tr id="holiday_<%= jpt_holiday_mst.id %>">
        <td><%= jpt_holiday_mst.id %></td>
        <td><%= jpt_holiday_mst.event_date.try(:strftime, '%Y/%m/%d') %></td>
        <td><%= jpt_holiday_mst.title %></td>
        <td><%= jpt_holiday_mst.description %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% if can? :update, @jpt_holiday_msts %>
  <%=render 'share/import_csv_modal',import_path: import_jpt_holiday_msts_path%>
<% end %>
<%= render 'new' %>
<%= render 'edit' %>

app/views/jpt_holiday_msts/update.js.erb
model = 'jpt_holiday_mst'

$('form#edit_' + model).clear_previous_errors()

<% if @jpt_holiday_mst.errors.any? %>
  $('form#edit_' + model).render_form_errors(model, '<%=@jpt_holiday_mst.errors.messages.to_json.html_safe%>')
<% else %>
  $('#holiday-edit-modal').modal('hide');
  $("#holiday_table").DataTable().row('tr.selected').remove();
  $('#holiday_table').DataTable().row.add([
    "<%=@jpt_holiday_mst.id%>",
    "<%=@jpt_holiday_mst.event_date.try(:strftime, '%Y/%m/%d')%>",
    "<%=@jpt_holiday_mst.title%>",
    "<%=@jpt_holiday_mst.description%>"
    ]).draw( false );
  $('#holiday_table').DataTable().buttons('#edit, #destroy').nodes().addClass('disabled');
<% end %>

app/views/jpt_holiday_msts/update_holiday.js.erb
model = 'jpt_holiday_mst'

$('form#edit_' + model).clear_previous_errors()

<% if @jpt_holiday_mst.errors.any? %>
  $('form#edit_' + model).render_form_errors(model, '<%=@jpt_holiday_mst.errors.messages.to_json.html_safe%>')
<% else %>
  $('#holiday-edit-modal').modal('hide');
  $("#holiday_table").DataTable().row('tr.selected').remove();
  $('#holiday_table').DataTable().row.add([
    "<%=@jpt_holiday_mst.id%>",
    "<%=@jpt_holiday_mst.event_date%>",
    "<%=@jpt_holiday_mst.title%>",
    "<%=@jpt_holiday_mst.description%>"
    ]).draw( false );
  $('#holiday_table').DataTable().buttons('#edit, #destroy').nodes().addClass('disabled');
<% end %>