config/routes.rb
Jpt::Application.routes.draw do
  Rails.application.routes.draw do
    resources :tasks do
      put :sort, on: :collection
      collection {post :change_status, :ajax}
    end
  end
  get 'rorumenbas/new'
  get 'kanris/index'
  get 'kanri/index'
  get 'main/search'
  get 'helps' => 'helps#index'
  get 'edit_help' => 'helps#edit_help'
  post 'helps' => 'helps#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "confirm" => "sessions#send_mail"
  post "confirm" => "sessions#confirm_mail"
  get "login_code" => "sessions#login_code"
  post "login_code" => "sessions#login_code_confirm"
  match 'main', to: 'main#index', via: [:get]

  resources :bashokubunmsts, :bunruis, :dengonkaitous, :dengonyoukens, :ekis, :jpt_holiday_msts,\
            :kairanyokenmsts, :kaishamasters, :kikanmsts, :rorumasters, :setsubis, :shainmasters,\
            :shozokumasters, :tsushinseigyous, :yakushokumasters do
    collection do
      get :export_csv
      post :import
    end
  end

  resources :conversations do
    collection {post :update_message}
    resources :messages
  end
  resources :yuusens do
    collection {get :export_csv}
    collection {post :import, :ajax}
  end
  resources :paths do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :settings do
    collection {post :import, :ajax}
    collection {get :export_csv, :setting}
  end

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end  

  resources :dengons do
    collection {get :export_csv}
  end

  resources :main, only: [:index] do
    collection {get :search}
    collection {post :ajax}
  end

  resources :shoninshamsts  do
    collection {post :import, :ajax, :create_shonin}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search,:pdf_show,:sumikakunin}
    collection {post :import, :ajax}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_mybasho,:create_basho,:update_basho, :create_kaisha,:update_kaisha, :create_job, :update_job, :time_line_view, :import, :shutchou_create}
    collection {get :time_line_view, :pdf_event_show, :pdf_job_show, :pdf_koutei_show, :shutchou_ikkatsu_new}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :mybashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :myjobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :ajax, :import}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search, :import}
    collection {get :shonin_search, :pdf_show, :show_keihi_shuppi,:pdf_show_keihi_shuppi, :pdf_show_index}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import, :multi_delete, :ajax, :create_joutai, :update_joutai}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
    collection {post :import,:ajax}
    collection {get :export_csv}
  end

  resources :yuukyuu_kyuuka_rirekis do
    collection { post :import, :ajax}
    collection {get :export_csv}
  end

  resources :rorumenbas do
    collection { post :import}
    collection {get :export_csv}
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection { post :import }
      collection { get :export_csv }
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end

  resources :kintaiteeburus do
    collection {post :import,:ajax}
  end
  
  root to: 'main#index'
end

app/models/eki.rb
class Eki < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:駅コード, :駅名, :駅名カナ]
  HEADERS = %w(駅コード 駅名 駅名カナ)
  PRIMARY_KEYS = %w(駅コード)

  self.table_name = :駅マスタ
  self.primary_key = :駅コード


  validates :駅コード, :駅名, presence: true
  validates :駅コード, uniqueness: true

  alias_attribute :id, :駅コード
  alias_attribute :name, :駅名

  def self.to_csv
    attributes = %w{駅コード 駅名 駅名カナ 選択回数}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |eki|
        csv << attributes.map{ |attr| eki.send(attr) }
      end
    end
  end

  # Naive approach
  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end

end

app/controllers/ekis_controller.rb
class EkisController < ApplicationController
  before_action :require_user!
  load_and_authorize_resource except: [:export_csv, :destroy, :update]
  respond_to :json, :js

  def index
    @ekis = Eki.all
    respond_with(@ekis)
  end

  def create
    @eki = Eki.new(eki_params)
    flash[:notice] = t 'app.flash.new_success' if @eki.save
    respond_with(@eki)
  end

  def update
    @eki = Eki.find_by(駅コード: eki_params[:駅コード])
    flash[:notice] = t 'app.flash.update_success' if @eki.update(eki_params)
    respond_with(@eki)
  end

  def destroy
    if params[:ids]
      Eki.where(id: params[:ids]).destroy_all
      data = { destroy_success: 'success' }
      respond_to do |format|
        format.json { render json: data }
      end
    else
      @eki = Eki.find_by_id(params[:id])
      @eki.destroy if @eki
      respond_with(@eki)
    end
  end

  def import
    if params[:file].nil?
      flash[:alert] = t 'app.flash.file_nil'
      redirect_to ekis_path
    elsif File.extname(params[:file].original_filename) != '.csv'
      flash[:danger] = t 'app.flash.file_format_invalid'
      redirect_to ekis_path
    else
      if notice = import_from_csv(Eki, params[:file])
        flash[:danger] = notice
        redirect_to ekis_path
      else
        notice = t 'app.flash.import_csv'
        redirect_to :back, notice: notice
      end
    end
  end

  def export_csv
    @ekis = Eki.all
    respond_to do |format|
      format.csv { send_data @ekis.to_csv, filename: '駅マスタ.csv' }
    end
  end

  private

  def eki_params
    params.require(:eki).permit(:駅コード, :駅名, :駅名カナ)
  end

end

app/helpers/ekis_helper.rb
module EkisHelper
end

app/views/ekis/_edit.html.haml
.modal#eki-edit-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel= (t 'title.ekihenshyuu')
      .modal-body
        = simple_form_for :eki, url: eki_path(id: 0), method: :patch, :remote => true, html: { id: 'edit_eki', role: :form, 'data-model' => 'eki'} do |f|
          = f.input :駅コード, label: (t 'title.ekicode'), as: :hidden
          = f.input :駅名 do
            = f.input_field :駅名, class: 'form-control'
            .span.help-block
          = f.input :駅名カナ, label: (t 'title.ekimeikana')
          = f.button :submit, class: 'btn btn-primary'

app/views/ekis/_new.html.haml
.modal#eki-new-modal{tabindex:-1, role: :dialog, 'aria-labelledby'=>"myModalLabel", 'aria-hidden'=>"true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times;
        %h4.modal-title#myModalLabel= (t 'title.ekishinki')
      .modal-body
        = simple_form_for :eki, url: ekis_path, method: :post, :remote => true, html: { id: 'new_eki', role: :form, 'data-model' => 'eki'} do |f|
          = f.input :駅コード do
            = f.input_field :駅コード, class: 'form-control'
            .span.help-block
          = f.input :駅名 do
            = f.input_field :駅名, class: 'form-control'
            .span.help-block
          = f.input :駅名カナ,label: (t 'title.ekimeikana')
          = f.button :submit, class: 'btn btn-primary'

app/views/ekis/create.js.erb
model = 'eki'

$('form#new_' + model).clear_previous_errors()

<% if @eki.errors.any? %>
  $('form#new_' + model).render_form_errors(model, '<%=@eki.errors.messages.to_json.html_safe%>')
<% else %>
  $('#eki-new-modal').modal('hide');
  $('#ekimaster').DataTable().row.add( [
    "<%=@eki.id%>",
    "<%=@eki.name%>",
    "<%=@eki.駅名カナ%>"
  ]).draw( false );
<% end %>

app/views/ekis/create_eki.js.erb
model = 'eki'

$('form#new_' + model).clear_previous_errors()

<% if @eki.errors.any? %>
  $('form#new_' + model).render_form_errors(model, '<%=@eki.errors.messages.to_json.html_safe%>')
<% else %>
  $('#eki-new-modal').modal('hide');
  $('#ekimaster').DataTable().row.add( [
    "<%=@eki.id%>",
    "<%=@eki.name%>",
    "<%=@eki.駅名カナ%>"
  ]).draw( false );
<% end %>

app/views/ekis/index.html.haml
= javascript_include_tag 'ekis/index'
= provide(:title, (t 'title.eki'))
%ol.breadcrumb
  %li= link_to (t 'title.menu'), main_path
  %li.active= (t 'title.ekimaster')

%table#ekimaster.table.table-striped.table-bordered.table-hover{cellspacing:0, width: '100%'}
  %thead
    %tr
      %th= (t 'title.ekicode')
      %th= (t 'title.ekimei')
      %th= (t 'title.ekimeikana')
  %tbody
    - @ekis.each do |eki|
      %tr
        %td= eki.id
        %td= eki.name
        %td= eki.駅名カナ
- if can? :update, @ekis
  = render 'share/import_csv_modal' ,import_path: import_ekis_path
= render 'new'
= render 'edit'

app/views/ekis/update.js.erb
model = 'eki'

$('form#edit_' + model).clear_previous_errors()

<% if @eki.errors.any? %>
  $('form#edit_' + model).render_form_errors(model, '<%=@eki.errors.messages.to_json.html_safe%>')
<% else %>
  $('#eki-edit-modal').modal('hide');
  $("#ekimaster").DataTable().row('tr.selected').remove();
  $('#ekimaster').DataTable().row.add([
    "<%=@eki.id%>",
    "<%=@eki.name%>",
    "<%=@eki.駅名カナ%>"
    ]).draw( false );
  $('#ekimaster').DataTable().buttons('#edit, #destroy').nodes().addClass('disabled');
<% end %>

app/views/ekis/update_eki.js.erb
model = 'eki'

$('form#edit_' + model).clear_previous_errors()

<% if @eki.errors.any? %>
  $('form#edit_' + model).render_form_errors(model, '<%=@eki.errors.messages.to_json.html_safe%>')
<% else %>
  $('#eki-edit-modal').modal('hide');
  $("#ekimaster").DataTable().row('tr.selected').remove();
  $('#ekimaster').DataTable().row.add([
    "<%=@eki.id%>",
    "<%=@eki.name%>",
    "<%=@eki.駅名カナ%>"
    ]).draw( false );
  $('#ekimaster').DataTable().buttons('#edit, #destroy').nodes().addClass('disabled');
<% end %>